plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  'winston-transport@*':
    dependencies:
      logform: '*'
  '@monstrs/log@*':
    dependencies:
      logform: '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/microservices': '*'
  '@nestjs/mapped-types@*':
    peerDependencies:
      'class-transformer': '*'
  '@nestjs/typeorm@*':
    dependencies:
      'rxjs': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/microservices': '*'
      '@nestjs/websockets': '*'
      'reflect-metadata': '*'
      'rxjs': '*'
  '@nestjs/common@*':
    dependencies:
      '@nestjs/platform-express': '*'
      'class-transformer': '*'
      'class-validator': '*'
      'cache-manager': '*'
      'reflect-metadata': '*'
      'rxjs': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      'reflect-metadata': '*'
      'grpc': '*'
      'rxjs': '*'
  debug@*:
    dependencies:
      'supports-color': '*'
  'follow-redirects@*':
    dependencies:
      debug: '*'
  'typeorm@*':
    dependencies:
      pg-query-stream: '*'
      sqlite3: '*'
      pg: '*'
  'pg-cursor@*':
    dependencies:
      pg: '*'
  'wolkenkit@*':
    dependencies:
      'json-schema': '*'
