plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  'winston-transport@*':
    dependencies:
      logform: '*'
  '@monstrs/log@*':
    dependencies:
      logform: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/microservices': '*'
      '@nestjs/websockets': '*'
  '@nestjs/common@*':
    dependencies:
      '@nestjs/platform-express': '*'
      'class-transformer': '*'
      'class-validator': '*'
      'cache-manager': '*'
  '@nestjs/microservices@*':
    dependencies:
      'amqp-connection-manager': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      'reflect-metadata': '*'
      'kafkajs': '*'
      'amqplib': '*'
      'redis': '*'
      'mqtt': '*'
      'nats': '*'
      'grpc': '*'
      'rxjs': '*'
  debug@*:
    dependencies:
      'supports-color': '*'
  'follow-redirects@*':
    dependencies:
      debug: '*'
  'mqtt@*':
    dependencies:
      duplexify: '*'
      'safe-buffer': '*'
  ws@*:
    dependencies:
      'utf-8-validate': '*'
      bufferutil: '*'
