packageExtensions:
  '@monstrs/log@*':
    dependencies:
      logform: '*'
  '@monstrs/typeorm-logger@*':
    dependencies:
      typeorm: '*'
  '@nestjs/common@*':
    dependencies:
      '@nestjs/platform-express': '*'
      cache-manager: '*'
      class-transformer: '*'
      class-validator: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/mapped-types@*':
    peerDependencies:
      class-transformer: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      grpc: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'
  winston-transport@*:
    dependencies:
      logform: '*'
  wolkenkit@*:
    dependencies:
      json-schema: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - .yarn/plugins/@monstrs/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-2.4.1.cjs
