packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'
  wolkenkit@*:
    dependencies:
      json-schema: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - .yarn/plugins/@monstrs/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-2.4.1.cjs
